- hosts: all
  tasks:
    - name: Insert below lines at the end of a file.
      blockinfile: 
       dest: /etc/sysctl.conf 
       block: |
               net.ipv6.conf.all.disable_ipv6=1
               net.ipv6.conf.default.disable_ipv6=1
